name: Generate RDF from Google doc

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "src/convert_to_rdf.py"
      - ".github/workflows/generate-rdf.yml"
  # schedule:
  #   - cron: '0 2 * * *'
  # Everyday at 2am

jobs:
  generate-rdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Download Excel files from Google docs
        run: |
          mkdir -p data/output
          wget -O data/food-claims-kg.xlsx "https://docs.google.com/spreadsheets/d/11SElScyLIs0RANYcT2MpWa7QWf-gIB13fjNvV9b5ZBE/export?format=xlsx&id=11SElScyLIs0RANYcT2MpWa7QWf-gIB13fjNvV9b5ZBE"

      - name: Convert Excel to RDF
        run: |
          python src/convert_to_rdf.py

      - name: SHACL validation
        run: |
          pyshacl -s shacl/neurodkg-shape.ttl -m -i rdfs -a -f human data/output/neuro_dkg.ttl

      - name: Upload output RDF data
        uses: actions/upload-artifact@v1
        with:
          name: rdf-output
          path: data

      - name: Clear older graph
        uses: vemonet/sparql-operations-action@v1
        with:
          query: "CLEAR GRAPH <https://w3id.org/neurodkg/graph>"
          endpoint: https://graphdb.dumontierlab.com/repositories/NeuroDKG/statements
          user: ${{ secrets.GRAPHDB_USER }}
          password: ${{ secrets.GRAPHDB_PASSWORD }}

      - uses: MaastrichtU-IDS/RdfUpload@master
        with:
          file: data/output/neuro_dkg.ttl
          endpoint: https://graphdb.dumontierlab.com/repositories/NeuroDKG/statements
          user: ${{ secrets.GRAPHDB_USER }}
          password: ${{ secrets.GRAPHDB_PASSWORD }}
          graph: "https://w3id.org/neurodkg/graph"
